# Generated by Django 5.0.1 on 2024-11-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecpies', '0007_remove_userprofile_needs_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingridents',
            field=models.CharField(max_length=500),
        ),
    ]
